"""Added table BlackboxComment

Revision ID: 157613737f97
Revises: 85e1fed29ed5
Create Date: 2023-07-29 22:44:33.363152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157613737f97'
down_revision = '85e1fed29ed5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blackbox',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fios', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('phone_formatted', sa.String(), nullable=True),
    sa.Column('tracks', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blackbox')
    # ### end Alembic commands ###
