"""fixed registration_date field to datetime

Revision ID: 54b02ed21f91
Revises: 98dc4f26e363
Create Date: 2023-09-05 22:16:08.467053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b02ed21f91'
down_revision = '98dc4f26e363'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'registration_date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'registration_date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
