"""Added reports and users tables

Revision ID: 6b68a65e4ee7
Revises: 157613737f97
Create Date: 2023-08-17 01:37:12.195805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b68a65e4ee7'
down_revision = '157613737f97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ext_id', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('nezabrav', 'blackbox', 'otzyvua', name='esource'), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('extra_names', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('report', sa.String(), nullable=False),
    sa.Column('TTN', sa.String(), nullable=True),
    sa.Column('carrier', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('warehouse', sa.String(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('shipment_date', sa.DateTime(), nullable=True),
    sa.Column('images', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('users')
    # ### end Alembic commands ###
