"""Changed field phone - nullable=True

Revision ID: 85e1fed29ed5
Revises: b5e631a5131f
Create Date: 2023-07-27 23:41:25.226081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e1fed29ed5'
down_revision = 'b5e631a5131f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otzyvua', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('otzyvua', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('otzyvua', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otzyvua', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('otzyvua', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('otzyvua', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
