"""Changed Users, added relationship in Users an Reports

Revision ID: 98dc4f26e363
Revises: 9b294ebd55cb
Create Date: 2023-09-04 23:24:27.230559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '98dc4f26e363'
down_revision = '9b294ebd55cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('registration_date', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'user', name='erole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ext_id', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('nezabrav', 'blackbox', 'otzyvua', name='esource'), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('extra_names', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('report', sa.String(), nullable=False),
    sa.Column('TTN', sa.String(), nullable=True),
    sa.Column('carrier', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('warehouse', sa.String(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('shipment_date', sa.DateTime(), nullable=True),
    sa.Column('images', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('blackbox')
    op.drop_table('otzyvua')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otzyvua',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('advantages', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('disadvantages', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('images', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='otzyvua_pkey')
    )
    op.create_table('blackbox',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fios', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone_formatted', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tracks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='blackbox_pkey')
    )
    op.drop_table('reports')
    op.drop_table('users')
    # ### end Alembic commands ###
