"""Added to column role default value

Revision ID: 9b294ebd55cb
Revises: be8d8e265d8f
Create Date: 2023-09-04 23:22:15.056118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b294ebd55cb'
down_revision = 'be8d8e265d8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
