"""Changed fields advantages, disadvantages

Revision ID: b5e631a5131f
Revises: f5efc4348f8a
Create Date: 2023-07-27 23:23:43.897497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e631a5131f'
down_revision = 'f5efc4348f8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
