"""Initial migration

Revision ID: f5efc4348f8a
Revises: 
Create Date: 2023-07-27 22:16:39.206753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5efc4348f8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otzyvua',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('advantages', sa.String(), nullable=True),
    sa.Column('disadvantages', sa.String(), nullable=True),
    sa.Column('images', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('otzyvua')
    # ### end Alembic commands ###
